export const metadata = {
    title: "About Page",
    description: "Generated by create next app",
};


export default function about() {
    return (
        <main>
            <h1>
                dkhferiufhvrfhcndjvb
            </h1>
        </main>
    )
}